### PR TITLE
JavaScript refactoring

### PR DESCRIPTION
**Pull request by johanbove**
Hi Nils,

I've rewritten the JS code into modules so the global window object is cleaner. Added comments and made sure the code passes Jshint rules. I also added gitignore etc files. Plus translated to English and set the location to Düsseldorf but I reverted back to German and your location for this PR;

Cheers,
Johan

### CODE REVIEW

**Comment by nils-werner** [comment]
Thanks! Unfortunately a few other changes also "crept in" :-)

 - We do not need `.gitignore` settings for Eclipse, Visual Studio and Python here [(you can define a system-wide gitignore to ignore IDE and editor specifics without having to do so in every repo individually)](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)
 - `.gitattributes` is not needed
 - In `manifest.json` there is still some data from your project
 - I appreciate the humidity graph but don't need it. Also I don't particularily like the choice of color. Could you give it a different color and make it optional?

**Comment by johanbove** [comment]
Sure, I'll remove the gitignore and gitattributes files.
I'll fix the manifest.json changes. Sorry about that.
i'll just remove the call to initialize the humidity graph. Not sure how I
would make it "optional" though other from removing the HTML and taking out
the plot call.

On Thu, Dec 3, 2015 at 5:55 PM, Nils Werner <notifications@github.com>
wrote:

> Thanks! Unfortunately a few other changes also "crept in" :-)
>
>    - We do not need .gitignore settings for Eclipse, Visual Studio and
>    Python here (you can define a system-wide gitignore to ignore IDE and
>    editor specifics without having to do so in every repo individually)
>    <https://help.github.com/articles/ignoring-files/#create-a-global-gitignore>
>    - .gitattributes is not needed
>    - In manifest.json there is still some data from your project
>    - I appreciate the humidity graph but don't need it. Also I don't
>    particularily like the choice of color. Could you give it a different color
>    and make it optional?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nils-werner/owm-display/pull/2#issuecomment-161714044>
> .
>



-- 
Johan

--
http://johanbove.info

**Comment by johanbove** [comment]
Nice work by the way. Cool implementation of the weather data. Which editor are you using to work on your programs?

**Comment by nils-werner** [comment]
Squashed and merged in a6d6de7e01

**Comment by nils-werner** [comment]
Thanks! Am using Atom, why?

**Comment by johanbove** [comment]
I'm just curious. I'm testing out Vscode myself.


On Fri, Dec 4, 2015 at 2:16 PM, Nils Werner <notifications@github.com>
wrote:

> Thanks! Am using Atom, why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nils-werner/owm-display/pull/2#issuecomment-161965098>
> .
>



-- 
Johan

--
http://johanbove.info

**Pull request closed without merging**
